variant: fcos
version: 1.6.0

ignition:
  config:
    merge:
      - local: 'dist/common/user-core.ign'
      - local: 'dist/common/user-worker.ign'
      - local: 'dist/common/unprivileged-ports.ign'
      - local: 'dist/common/qemu-guest-agent.ign'
      - local: 'dist/common/disable-ipv6.ign'
      - local: 'dist/common/secrets-loader.ign'

storage:
  files:
    - path: /home/worker/.config/containers/systemd/user/tang.container
      contents:
        local: tang.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/secrets/k2qeJ4Jnxd-1uXQcrUb7IL4Z0P9j1UDsU0wFE3vWRww.jwk.jwe
      contents:
        local: jwks/k2qeJ4Jnxd-1uXQcrUb7IL4Z0P9j1UDsU0wFE3vWRww.jwk.jwe
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/secrets/NH3kJu1a6rxRMoqBJzuE-z17fDJbGDkYko-C9mACv3A.jwk.jwe
      contents:
        local: jwks/NH3kJu1a6rxRMoqBJzuE-z17fDJbGDkYko-C9mACv3A.jwk.jwe
      user:
        name: worker
      group:
        name: worker
