variant: fcos
version: 1.6.0

ignition:
  config:
    merge:
      - local: 'dist/common/user-core.ign'
      - local: 'dist/common/user-worker.ign'
      - local: 'dist/common/unprivileged-ports.ign'
      - local: 'dist/common/qemu-guest-agent.ign'
      - local: 'dist/common/disable-ipv6.ign'
      - local: 'dist/common/secrets-loader.ign'
      - local: 'dist/common/main-disk-encrypted.ign'

storage:
  directories:
    - path: /home/worker/caddy
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/data
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/conf
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/build
      user:
        name: worker
      group:
        name: worker        

  files:
    - path: /home/worker/.config/containers/systemd/user/caddy.build
      contents:
        local: caddy.build
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/caddy.container
      contents:
        local: caddy.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/conf/Caddyfile
      contents: 
        local: Caddyfile
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/secrets/cloudflare-api-key.jwe
      contents: 
        local: cloudflare-api-key.jwe
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/build/Dockerfile
      contents: 
        local: Dockerfile
      user:
        name: worker
      group:
        name: worker
