variant: fcos
version: 1.6.0

ignition:
  config:
    merge:
      - local: 'dist/common/user-core.ign'
      - local: 'dist/common/user-worker.ign'
      - local: 'dist/common/unprivileged-ports.ign'
      - local: 'dist/common/qemu-guest-agent.ign'
      - local: 'dist/common/disable-ipv6.ign'
      - local: 'dist/common/secrets-loader.ign'

storage:
  directories:
    - path: /home/worker/netbird
      user: 
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/data
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/conf
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/build
      user:
        name: worker
      group:
        name: worker        
  files:
    - path: /home/worker/secrets/nb-setup-key.jwe
      contents:
        local: nb-setup-key.jwe
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/netbird.container
      contents:
        local: netbird.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/caddy.build
      contents:
        local: caddy.build
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/caddy.container
      contents:
        local: caddy.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/conf/Caddyfile
      contents: 
        local: Caddyfile
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/secrets/cloudflare-api-key.jwe
      contents: 
        local: cloudflare-api-key.jwe
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/build/Dockerfile
      contents: 
        local: Dockerfile
      user:
        name: worker
      group:
        name: worker

systemd:
  units:
    - name: netbird-setup.service
      enabled: true
      contents: |
        [Unit]
        Description=Setup for Netbird

        [Service]
        Type=oneshot
        ExecStart=/usr/sbin/sysctl -w net.ipv4.conf.all.src_valid_mark=1
        RemainAfterExit=true

        [Install]
        WantedBy=multi-user.target
