variant: fcos
version: 1.6.0

ignition:
  config:
    merge:
      - local: 'dist/common/user-core.ign'
      - local: 'dist/common/user-worker.ign'
      - local: 'dist/common/disable-ipv6.ign'
      - local: 'dist/common/unprivileged-ports.ign'
      - local: 'dist/common/qemu-guest-agent.ign'
      - local: 'dist/common/data-disk-plain.ign'

storage:
  directories:
    - path: /var/mnt/data/shared
      user: 
        name: worker
      group:
        name: worker
  files:
    - path: /home/worker/.config/containers/systemd/user/samba.container
      contents:
        local: samba.container
      user:
        name: worker
      group:
        name: worker
