variant: fcos
version: 1.6.0

ignition:
  config:
    merge:
      - local: 'dist/common/user-core.ign'
      - local: 'dist/common/user-worker.ign'
      - local: 'dist/common/unprivileged-ports.ign'
      - local: 'dist/common/qemu-guest-agent.ign'
      - local: 'dist/common/disable-ipv6.ign'
storage:
  directories:
    - path: /home/worker/adguard
      user:
        name: worker
      group:
        name: worker
  files:
    - path: /home/worker/.config/containers/systemd/user/adguard.container
      contents:
        local: adguard.container
      user:
        name: worker
      group:
        name: worker
    # Note: not using the secrets-loader module here because AdGuard insists on being able to make changes to the file.
    - path: /home/worker/adguard/AdGuardHome.yaml.jwe
      contents:
        local: AdGuardHome.yaml.jwe
      user:
        name: worker
      group:
        name: worker
    - path: /etc/systemd/resolved.conf.d/adguardhome.conf
      contents:
        local: resolve.conf
