variant: fcos
version: 1.6.0

ignition:
  config:
    merge:
      - local: 'dist/common/user-core.ign'
      - local: 'dist/common/user-worker.ign'
      - local: 'dist/common/unprivileged-ports.ign'
      - local: 'dist/common/qemu-guest-agent.ign'
      - local: 'dist/common/data-disk-plain.ign'
      - local: 'dist/common/disable-ipv6.ign'
      - local: 'dist/common/secrets-loader.ign'

storage:
  disks:
    - device: /dev/sdc
      partitions:
        - number: 1
          label: config

  filesystems:
    - device: /dev/disk/by-partlabel/config
      path: /var/mnt/config
      format: ext4
      with_mount_unit: true

  directories:
    - path: /var/mnt/data/jellyfin
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/jellyfin/cache
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/jellyfin/media
      user: 
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/downloads
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/config/jellyfin
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/config/qbittorrent
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/config/sonarr
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/config/prowlarr
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/config/radarr
      user:
        name: worker
      group:
        name: worker
    - path: /var/mnt/config/bazarr
      user:
        name: worker
      group:
        name: worker
    - path: /var/mnt/config/caddy
      user:
        name: worker
      group:
        name: worker

  files:
    - path: /home/worker/.config/containers/containers.conf 
      contents:
        local: containers.conf
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/jellyfin.network
      contents:
        local: jellyfin.network
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/jellyfin.container
      contents:
        local: jellyfin.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/qbittorrent.container
      contents:
        local: qbittorrent.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/sonarr.container
      contents:
        local: sonarr.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/prowlarr.container
      contents:
        local: prowlarr.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/radarr.container
      contents:
        local: radarr.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/bazarr.container
      contents:
        local: bazarr.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/caddy.container
      contents:
        local: caddy.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/caddy/Caddyfile
      contents:
        local: Caddyfile
      user:
        name: worker
      group:
        name: worker
