variant: fcos
version: 1.6.0

ignition:
  config:
    merge:
      - local: 'dist/common/user-core.ign'
      - local: 'dist/common/user-worker.ign'
      - local: 'dist/common/unprivileged-ports.ign'
      - local: 'dist/common/qemu-guest-agent.ign'
      - local: 'dist/common/disk-data-plain.ign'
      - local: 'dist/common/disable-ipv6.ign'
      - local: 'dist/common/secrets-loader.ign'

storage:
  directories:
    - path: /var/mnt/data/jellyfin
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/jellyfin/cache
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/jellyfin/config
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/jellyfin/media
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/qbittorrent/config
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/downloads
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/sonarr/config
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/prowlarr/config
      user: 
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/radarr/config
      user:
        name: worker
      group:
        name: worker
    - path: /var/mnt/data/netbird      
      user:
        name: worker
      group:
        name: worker
  files:
    - path: /home/worker/.config/containers/systemd/user/jellyfin.network
      contents:
        inline: |
          [Network]

          [Install]
          WantedBy=multi-user.target
    - path: /home/worker/.config/containers/containers.conf 
      contents:
        inline: |
          [network]
          default_rootless_network_cmd="slirp4netns"
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/jellyfin.container
      contents:
        local: jellyfin.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/qbittorrent.container
      contents:
        local: qbittorrent.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/sonarr.container
      contents:
        local: sonarr.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/prowlarr.container
      contents:
        local: prowlarr.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/radarr.container
      contents:
        local: radarr.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/.config/containers/systemd/user/netbird.container
      contents:
        local: netbird.container
      user:
        name: worker
      group:
        name: worker
