variant: fcos
version: 1.5.0

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKF05sq4UVmmh8qfIQt4y6c8SjtJ7Q0sEvoAg7tlP+Mo

systemd:
  units:
    - name: minecraft.service
      enabled: true
      contents: |
        [Unit]
        Description=Minecraft
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        Restart=always
        Environment="BASE_PATH=/home/core/minecraft"
        ExecStart=/bin/bash /home/core/minecraft/run.sh

        [Install]
        WantedBy=multi-user.target
storage:
  disks:
    - device: /dev/sdb
      partitions:
        - number: 1
          label: data
  filesystems:
    - device: /dev/disk/by-partlabel/data
      path: /var/data
      format: ext4
      with_mount_unit: true
  files:
    - path: /home/core/minecraft/run.sh
      contents:
        local: run.sh
    - path: /home/core/minecraft/minecraft.env
      contents:
        local: minecraft.env
