variant: fcos
version: 1.5.0

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKF05sq4UVmmh8qfIQt4y6c8SjtJ7Q0sEvoAg7tlP+Mo

systemd:
  units:
    - name: tang.service
      enabled: true
      contents: |
        [Unit]
        Description=Tang
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        Restart=always
        Environment="BASE_PATH=/home/core/tang"
        ExecStart=/bin/bash /home/core/tang/run.sh

        [Install]
        WantedBy=multi-user.target
storage:
  files:
    - path: /home/core/tang/run.sh
      contents:
        local: run.sh
boot_device:
  luks:
    tang:
      - url: http://10.0.10.111:9999
        thumbprint: hpQj54d1rmHroGCfZoM4_ZAlO3W1ZzGjKratbBxDKBw
      - url: http://10.0.31.30:9999
        thumbprint: 37dTqKL28NLyitb6KdohiA4PFcNcKIsQ7r-5gNuNapg
      - url: http://10.0.32.30:9999
        thumbprint: k2qeJ4Jnxd-1uXQcrUb7IL4Z0P9j1UDsU0wFE3vWRww
    threshold: 1
