variant: fcos
version: 1.6.0

ignition:
  config:
    merge:
      - local: 'dist/common/user-core.ign'
      - local: 'dist/common/user-worker.ign'
      - local: 'dist/common/unprivileged-ports.ign'
      - local: 'dist/common/qemu-guest-agent.ign'
      - local: 'dist/common/main-disk-encrypted.ign'
      - local: 'dist/common/data-disk-encrypted.ign'
      - local: 'dist/common/disable-ipv6.ign'

storage:
  directories:
    - path: /home/worker/conduwuit
      user: 
        name: worker
      group:
        name: worker
  files:
    - path: /home/worker/.config/containers/systemd/user/conduwuit.container
      contents:
        local: conduwuit.container
      user:
        name: worker
      group:
        name: worker
    - path: /home/worker/conduwuit/conduwuit.env
      contents: 
        local: conduwuit.env
      user:
        name: worker
      group:
        name: worker
